before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt55 -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
install:
    - sudo apt-get install g++-5 qt55base qt55serialport
script:
    - source /opt/qt55/bin/qt55-env.sh
    - mkdir build
    - cd build
    - qmake QMAKE_CC=gcc-5 QMAKE_CXX=g++-5 ../src/bullycpp.pro
    - make

